### ISSUE TITLE
Support namespace specification

### ISSUE THREAD

**Issue by LittleWat** [trinodb/charts#114]
Currently, the namespace option is ignored by the helm chart.

```shell
helm template . --namespace <my_namespace>
```

I want to include the namespace in the output resources and am glad if this is supported.

**Comment by nineinchnick** [comment]
Why do you need the namespace to be present in rendered manifest files?

**Comment by LittleWat** [comment]
we are using `helm template --namespace` command in our CI/CD pipeline to generate the manifests based on the values.yaml file and the FluxCD applies the generated manifest to our k8s cluster using `kustomize`. (not using `helm install`)
The other Helm charts such as Superset support this so I want to make it possible to specify the namespace in Trino as well.
https://github.com/apache/superset/blob/2fdf6d7b6484c4110d06e90605dae405a6df38f8/helm/superset/templates/secret-superset-config.yaml#L24

Does it make sense...?
