### ISSUE TITLE
Support multiple authentication types

### ISSUE THREAD

**Issue by viktor-legachev-quantori** [trinodb/charts#118]
Trino supports multiple authentication types: https://trino.io/docs/current/security/authentication-types.html#multiple-authentication-types
Current chart oriented for single-valued auth type.

**Comment by philicious** [comment]
@viktor-legachev-quantori I assume you tried a combination of `PASSWORD` + sth else? 
as only for `PASSWORD` I see the chart being limited to single-value https://github.com/search?q=repo%3Atrinodb%2Fcharts%20.Values.server.config.authenticationType&type=code

**Comment by philicious** [comment]
ah, its being fixed in https://github.com/trinodb/charts/pull/124

**Comment by viktor-legachev-quantori** [comment]
@philicious yes, you're right, I was talking about PASSWORD + sth else, OAUTH2 in my case.
Thank you for response, will take a look later.
