### ISSUE TITLE
dynamic catalog.management

### ISSUE THREAD

**Issue by stefanondisponibile** [trinodb/charts#128]
Currently it is not possible to easily use `dynamic` catalog management because `ConfigMaps` are mounted as ReadOnly into the coordinator Pod.

It would be nice having a way to work around that, do you have any ideas? Creating an EmptyDir and then moving the files from the current ConfigMap there?

**Comment by jonathanbisp** [comment]
I really need this feature, and I am not so deep in the project. However, what about use a PersistentVolumeClaim instead? So we will be able to restart the coordinator, without lost the changes.

**Comment by nineinchnick** [comment]
You can mount a persistent volume and change the directory where Trino keeps catalogs. Here's an example how it can be done: https://github.com/trinodb/charts/pull/178

Until Trino changes default catalog management from static to dynamic, I don't think there are any changes required in the chart.

**Comment by nsoria1** [comment]
What about now? I think the option to make it dynamically is available but the example values are not showing how to achieve it
