### ISSUE TITLE
Security configuration in trinodb helm chart

### ISSUE THREAD

**Issue by optimus-kart** [trinodb/charts#136]
Helm chart available here: https://github.com/trinodb/charts , does not seem to provide an option to configure authentication/authorization for trinodb, is this intentionally left out? If not I could take this up and try to add this functionality to the chart.

Kindly advise.

**Comment by hashhar** [comment]
there's now `server.config.authenticationType` for this.

See https://github.com/trinodb/charts/blob/main/charts/trino/README.md.
