### ISSUE TITLE
Setting `additionalLogProperties` gives error

### ISSUE THREAD

**Issue by xiaoPierre** [trinodb/charts#141]
Hello, 

I was trying to set some logging properties with `additionalLogProperties` field, with something like 

```
additionalLogProperties:
  - "log.path=var/log/server.log"
``` 

However I got an error `java.lang.IllegalArgumentException: No enum constant io.airlift.log.Level./VAR/LOG/SERVER.LOG`

After some trials, I found out that [the logging properties](https://trino.io/docs/current/admin/properties-logging.html) may need to be set in `config.properties` instead of `log.properties`, which is supposed to contain only log level. 

Would someone be able to valid that it's a valid issue, and confirm whether the similar issue exists for other `additional*` variables in the chart ? Thanks in advance.

**Comment by mosabua** [comment]
Log properties should be set in log.properties file .. which is what the chart does. The additionalLogProperties be single log lines for that file in the format package=loglevel

The linked logging properties are for configuring logging .. not for setting log levels. It might be a bit badly named ...

**Comment by xiaoPierre** [comment]
Thanks for the explanation ! Closing the issue
