### ISSUE TITLE
feature request: choosing statefulSet instead of deployment

### ISSUE THREAD

**Issue by Viktor3434** [trinodb/charts#191]
Hello!
Please add the ability to choose statefulset instead of deployment.
if you can :)

UPD:
for workers
I need VolumeClaimTemplates

**Comment by Viktor3434** [comment]
This is needed to store cache and spills when deploying the chart to the cloud.

It should be easy to add a switch from deployment to statefulset.
You can take all the configuration from the deployment, and add the switch (in valuess) to the deployment section

in templates it is 2 if conditions
1 for kind 
2 for volumeClaimTemplates 
3 for volumeMounts

or add a separate template with a small modification.

Translated with DeepL.com (free version)

**Comment by nineinchnick** [comment]
Isn't cache and spills ephemeral? Why would you need to bind it to specific pods?

Are you interested in contributing this?

**Comment by nineinchnick** [comment]
We can't use any code you write if you don't sign the CLA.

The docs say to use a separate disk device to avoid saturating the IO, it doesn't mention anything about reusing the same spilled or cached data after a node restarts. 

You should still be able to use automatically provisioned volumes with deployments, and make sure you have some policy to clean up unused ones.

**Comment by mosabua** [comment]
I am not sure about the motivation for this change. It works perfectly fine to use spilling (not recommended but nevertheless) or file system caching as it stands now. What would the change to statefulSet actually fix or improve.

**Comment by Viktor3434** [comment]
Hi!
We are assuming cache + spills to be 200+ GB.
Kubernetes node volume is simply not enough in a normal configuration. 

I will prepare a PR if you are willing to consider it.

I also apologize for my English :)

**Comment by Viktor3434** [comment]
what do you think?

**Comment by nineinchnick** [comment]
You don't need StatefulSets for generic ephemeral volumes: https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes
