### ISSUE TITLE
Upgrading from 0.18 to 0.25 Changed the service name in k8s

### ISSUE THREAD

**Issue by ziot-arg** [trinodb/charts#196]
I was using 0.18 version, in the last days I upgraded to 0.25 but I noted that the service name of my trino changed:

Using this execution line:

`helm upgrade --install trino-cluster trino/trino  --namespace trino --create-namespace --version 0.18.0 -f values-prod1.yml
`
Creates:

```
kubectl get service -n trino
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
trino-cluster   ClusterIP   172.20.55.20   <none>        8080/TCP   104d
```

Now doing:
`helm upgrade --install trino-cluster trino/trino  --namespace trino--create-namespace --version 0.25.0 -f values-prod1.yml
`
Creates:
```
kubectl get service -n trino-stage
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
trino-cluster-trino   ClusterIP   172.20.151.41   <none>        8080/TCP          8d
```
Here you can see that the service changes from TRINO-CLUSTER to TRINO-CLUSTER-TRINO

**Comment by nineinchnick** [comment]
@ziot-arg what's the expected action here? Reverting this change would be another breaking change.
