### ISSUE TITLE
Unable to Set Resources for JMX Exporter in Trino Helm Chart

### ISSUE THREAD

**Issue by alaturqua** [trinodb/charts#202]
#### Description
Currently, the Trino Helm chart does not allow setting resource requests and limits for the JMX exporter. This limitation causes issues on Kubernetes clusters that require resource specifications for CPU and memory as a prerequisite.

#### Error Message
```
Error creating: pods "trino-helm-etl-coordinator-8655d99488-5jlwb" is forbidden: failed quota: quota-bitrino-dev: must specify limits.cpu for: jmx-exporter; limits.memory for: jmx-exporter; requests.cpu for: jmx-exporter; requests.memory for: jmx-exporter
```

#### Impact
This restriction prevents deployment on clusters with strict resource quota policies, hindering the ability to use the Trino Helm chart in such environments.

#### Suggested Solution
Please provide a way to configure resource requests and limits for the JMX exporter in the Helm chart values.

```[tasklist]
### Tasks
```

**Comment by rotem-ad** [comment]
We've also hit this issue. Opened a PR to resolve this
