### ISSUE TITLE
unable to parse key: interface conversion

### ISSUE THREAD

**Issue by jarlva** [trinodb/charts#205]
Hello, getting the following error in a brand new 0.26.0 chart install. 
It happens when I use the `--set global.image.tag` , like:

`helm install trino-sql -f deployments/k8s/values.yaml  --namespace trino-sql --set global.image.tag=latest deployments/k8s/`

```
Error: INSTALLATION FAILED: failed parsing --set data: unable to parse key: interface conversion: interface {} is nil, not map[string]interface {}
```

**Comment by nineinchnick** [comment]
If you're using this chart as a subchart, you'd have to share your umbrella chart. Please provide enough information on how to reproduce this issue.

**Comment by jarlva** [comment]
No umbrella chart. Using the default Chart.yaml file. Except changing v2 to v1:
`apiVersion: v1
`

**Comment by nineinchnick** [comment]
Please provide complete steps to reproduce the issue. Why are you changing `apiVersion` to v1?

**Comment by jarlva** [comment]
After some more digging found that the issue is not caused by the chart. Thanks!
