### ISSUE TITLE
Support adding entries to Pod /etc/hosts with HostAliases

### ISSUE THREAD

**Issue by acan107** [trinodb/charts#214]
I'm trying to deploy a Trino cluster with a Hive connector (to an HDFS file system) on Kubernetes. In the HDFS configuration files (e.g. core-site.xml), host names are used instead of IP addresses.

Last time I deployed a Trino cluster using Docker containers, and I could add entries to /etc/hosts using the --add-host="<host_name>:<host_ip>" flag when running the containers (docker run ...).

It seems that the trino chart hasn't supported this function yet. Could you help to add this support?
(I noticed that this support had been requested in issue #110, while not been accepted for some reason.)

**Comment by mosabua** [comment]
The original request was abandoned by the contributor. You can pick that up and drive it to completion. We (charts maintainers) are not planning to work on this ourselves.
