### ISSUE TITLE
Deployment coordinator not have replicas

### ISSUE THREAD

**Issue by minhpnz** [trinodb/charts#250]
Hi can you check on deployment coordinator seem like it is missing replicas 

> spec:
>   progressDeadlineSeconds: {{ .Values.coordinator.deployment.progressDeadlineSeconds }}
>   revisionHistoryLimit: {{ .Values.coordinator.deployment.revisionHistoryLimit }}
>   strategy:
>     {{- toYaml .Values.coordinator.deployment.strategy | nindent 4 }}
>  ==>  **replicas: {{ .Values.server.coordinator }}**  ==> Missing replicas
>   selector:
>     matchLabels:
>       {{- include "trino.selectorLabels" . | nindent 6 }}
>       app.kubernetes.io/component: coordinator
>   template:
>     metadata:
>       annotations:

**Comment by mosabua** [comment]
Just in case others are wondering - Trino works with one coordinator only per cluster. See https://trino.io/docs/current/overview/concepts.html#architecture
