### ISSUE TITLE
Class not found for  org.apache.hadoop.fs.s3a.S3AFileSystem

### ISSUE THREAD

**Issue by sushilkjaiswar** [trinodb/charts#264]
I am using trinodb/trino:462 image where it throws error when I am using minio configuration for iceberg,dleta-lake catalog confiuration and querying. Do we have to add addtional jars for this S# filesystem support org.apache.hadoop.fs.s3a.S3AFileSystem because from documentation it says it is packaged as a part of the image.

**Comment by nineinchnick** [comment]
Why do you think it might be an issue with the chart? What's the documentation you're referring to? Maybe ask for help on the Trino Slack.

**Comment by sushilkjaiswar** [comment]
I do not think it is issue with the chart but with docker image packaging. I thought this is official trinodb repository hence posted this issue here after going through exisiting issues reported and google for the issue. I will try to reach out to Trino Slack.  From documentation I referred official Trino doc - https://trino.io/docs/current/object-storage/file-system-s3.html and also explored charts default values.yaml to find if any settings are missing. 

Thank You

**Comment by sushilkjaiswar** [comment]
Closing this issue since this is not the right place to report.
